version: "3.4"

services:
    build-package:
        image: build-package:dev
        build:
            context: .
            target: build-package
        environment:
            R_BUILD_DIR: "${R_BUILD_DIR:-build}"
            R_BUILD_VIGNETTES: "${R_BUILD_VIGNETTES:-FALSE}"
        volumes:
            - "./${R_BUILD_DIR:-build}:/package/${R_BUILD_DIR:-build}"
        
    check-package:
        image: check-package:dev
        build:
            context: .
            target: check-package
        env_file: build.env
        volumes:
            - "./${R_BUILD_DIR:-build}:/package/${R_BUILD_DIR:-build}"

    knitr-paper:
        image: knitr-paper:dev
        build:
            context: .
            target: knitr-paper
        environment:
            KNITR_INPUT_FILE: PSplineInference.rnw
            KNITR_OUTPUT_DIR: "${KNITR_OUTPUT_DIR:-knitr}"
            KNITR_OUTPUT_FILE: "${KNITR_OUTPUT_DIR:-knitr}/PSplineInference.tex"
            KNITR_RUN_VALIDATION: "${KNITR_RUN_VALIDATION:-FALSE}"
        env_file: build.env
        volumes:
            - "./${R_BUILD_DIR:-build}:/tex/${R_BUILD_DIR:-build}"
            - "./${KNITR_OUTPUT_DIR:-knitr}:/tex/${KNITR_OUTPUT_DIR:-knitr}"
       
    pdflatex-figures:
        image: pdflatex-figures:dev
        environment:
            KNITR_OUTPUT_DIR: "${KNITR_OUTPUT_DIR:-knitr}"
        build:
            context: .
            target: pdflatex-figures
        volumes:
            - "./${KNITR_OUTPUT_DIR:-knitr}:/tex/${KNITR_OUTPUT_DIR:-knitr}"

    pdflatex-paper:
        image: pdflatex-paper:dev
        build:
            context: .
            target: pdflatex-paper
        environment: 
            ARG LATEX_FILE: PSplineInference.tex
        volumes:
            - ./overleaf:/tex
