stages:
  - tools
  - build
  - check
  - knitr
  - figures
  - exports
  - pdf

variables:
  R_BUILD_DIR: "package"
  KNITR_OUTPUT_DIR: "knitr"
  TEX_DIR: "Paper"
  OVERLEAF_ARTIFACTS_DIR: "overleaf"
  REVIEW_ARTIFACTS_DIR: "pspline-inference"
  COMPOSE_FILES: --file docker-compose.yml --file docker-compose-gitlab.yml

.docker:
    tags:
        - docker
    services:
        - docker:18.09.7-dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    image: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-compose-ci

tools:
  stage: tools
  extends: 
    - .docker
  script:
    - gitlab-docker-compose ${COMPOSE_FILES} --cache-from main package-tools paper-tools
  
.build:
  stage: build
  extends: 
    - .docker
  variables:
    R_PACKAGE_SOURCE: .
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run package-build
    - export R_PACKAGE_ARCHIVE=`ls "${R_BUILD_DIR}"/pspline.inference*.tar.gz | head -n1`
    - printenv | grep '^R_PACKAGE_ARCHIVE=' >> build.env
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-package"
    paths:
      - "${R_BUILD_DIR}"
      - build.env
    when: always
  
build:
  extends: .build
  variables:
    R_BUILD_VIGNETTES: "TRUE"
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^[Pp]aper([\/-].*)?$/ || $CI_COMMIT_REF_NAME =~ /^validation(-.*)?$/'
      when: manual
    - when: always
  
⚡️ build:
  extends: .build
  variables:
    R_BUILD_VIGNETTES: "FALSE"

check:
  stage: check
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run package-check
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^[Pp]aper([\/-].*)?$/ || $CI_COMMIT_REF_NAME =~ /^validation(-.*)?$/'
      when: manual
    - when: always
  needs:
    - build

.knitr:
  stage: knitr
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-knit
  needs:
    - ⚡️ build
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-knitr"
    paths:
      - "${KNITR_OUTPUT_DIR}"
    
knitr:
  extends: .knitr
  tags:
    - docker-cpu:comp8
  variables:
    KNITR_RUN_VALIDATION: "TRUE"
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^validation(-.*)?$/'
      when: always
    - when: manual

⚡️ knitr:
  extends: .knitr
  tags:
    - docker-mem:3
  variables:
    KNITR_RUN_VALIDATION: "FALSE"

# figures:
#   stage: figures
#   extends: 
#     - .docker
#   script:
#     - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
#     - docker-compose ${COMPOSE_FILES} run paper-figures
#   artifacts:
#     name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-figures"
#     paths:
#       - "${KNITR_OUTPUT_DIR}/figures/*.pdf"
#       - "${KNITR_OUTPUT_DIR}/figures/*.tif"

overleaf:
  stage: exports
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-overleaf
  needs:
    - ⚡️ knitr
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-overleaf"
    paths:
      - "${OVERLEAF_ARTIFACTS_DIR}"

# plos-comp-biol:
#   stage: exports
#   extends: 
#     - .docker
#   script:
#     - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
#     - docker-compose ${COMPOSE_FILES} run paper-plos-comp-biol
#   artifacts:
#     name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-plos-comp-biol"
#     paths:
#       - '${REVIEW_ARTIFACTS_DIR}/*.tex'
#       - '${REVIEW_ARTIFACTS_DIR}/Fig*.tif'
#       - '${REVIEW_ARTIFACTS_DIR}/*.pdf'

pdf:
  stage: pdf
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-pdf
    - mv "${OVERLEAF_ARTIFACTS_DIR}/PSplineInference.pdf" .
  needs:
    - overleaf
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-pdf"
    paths:
      - "PSplineInference.pdf"
