stages:
  - tools
  - build
  - check
  - knitr
  - figures
  - exports
  - pdf

variables:
  R_BUILD_DIR: "build"
  KNITR_OUTPUT_DIR: "knitr"
  TEX_DIR: "Paper"
  OVERLEAF_ARTIFACTS_DIR: "overleaf"
  REVIEW_ARTIFACTS_DIR: "pspline-inference"
  COMPOSE_FILES: --file docker-compose.yml --file docker-compose-gitlab.yml

.docker:
    tags:
        - docker
    services:
        - docker:18.09.7-dind
    image: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-compose-ci

tools:
  stage: tools
  extends: 
    - .docker
  script:
    - gitlab-docker-compose ${COMPOSE_FILES} --cache-from main package-tools paper-tools
  
.build:
  stage: build
  extends: 
    - .docker
  variables:
    R_PACKAGE_SOURCE: .
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run package-build
    - export R_PACKAGE_ARCHIVE=`ls "${R_BUILD_DIR}"/pspline.inference*.tar.gz | head -n1`
    - printenv | grep '^R_PACKAGE_ARCHIVE=' >> build.env
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-package"
    paths:
      - "${R_BUILD_DIR}"
      - build.env
    when: always
  
build:
  extends: .build
  variables:
    BUILD_VIGNETTES: "TRUE"
  except: 
    - /^[Pp]aper([/-].*)?$/
    - /^validation(-.*)?$/
  
⚡️ build:
  extends: .build
  variables:
    BUILD_VIGNETTES: "FALSE"

check:
  stage: check
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run package-check
  except:
    - /^[Pp]aper([/-].*)?$/
    - /^validation(-.*)?$/
  dependencies:
    - build

.knitr:
  stage: knitr
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-knit
  dependencies:
    - ⚡️ build
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-knitr"
    paths:
      - "${KNITR_OUTPUT_DIR}"
    
knitr:
  extends: .knitr
  tags:
    - docker-cpu:comp8
  variables:
    RUN_VALIDATION: "TRUE"
  only:
    - /^validation(-.*)?$/

⚡️ knitr:
  extends: .knitr
  tags:
    - docker-mem:3
  variables:
    RUN_VALIDATION: "FALSE"
  only:
    - /^[Pp]aper([/-].*)?$/

figures:
  stage: figures
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-figures
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-figures"
    paths:
      - "${KNITR_OUTPUT_DIR}/figures/*.pdf"
      - "${KNITR_OUTPUT_DIR}/figures/*.tif"
  only:
    - /^[Pp]aper([/-].*)?$/

overleaf:
  stage: exports
  extends: 
    - .docker
  script:
    - mkdir -p "${OVERLEAF_ARTIFACTS_DIR}/figures"
    - cp "${KNITR_OUTPUT_DIR}/PSplineInference.tex" "${TEX_DIR}/plos2015.bst" "${TEX_DIR}/PSplineInference.bib" "${OVERLEAF_ARTIFACTS_DIR}"
    - cp "${KNITR_OUTPUT_DIR}"/figures/*.tex "${OVERLEAF_ARTIFACTS_DIR}/figures"
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-overleaf"
    paths:
      - "${OVERLEAF_ARTIFACTS_DIR}"
  only:
    - /^[Pp]aper([/-].*)?$/

plos-comp-biol:
  stage: exports
  extends: 
    - .docker
  script:
    - mkdir -p "${REVIEW_ARTIFACTS_DIR}"
    - cp "${KNITR_OUTPUT_DIR}/figures"/*.tif  "${REVIEW_ARTIFACTS_DIR}"
    - cp "${KNITR_OUTPUT_DIR}/PSplineInference.tex" "${TEX_DIR}/plos2015.bst" "${TEX_DIR}/PSplineInference.bib" "${REVIEW_ARTIFACTS_DIR}"
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-plos-comp-biol
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-overleaf"
    paths:
      - '${REVIEW_ARTIFACTS_DIR}/*.tex'
      - '${REVIEW_ARTIFACTS_DIR}/*.tif'
      - '${REVIEW_ARTIFACTS_DIR}/*.pdf'
  only:
    - /^[Pp]aper([/-].*)?$/

pdf:
  stage: pdf
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-pdf
    - mv "${OVERLEAF_ARTIFACTS_DIR}/PSplineInference.pdf" .
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-pdf"
    paths:
      - "PSplineInference.pdf"
  only: 
    - /^[Pp]aper([/-].*)?$/
