stages:
  - tools
  - build
  - check
  - knitr
  - overleaf
  - tex

variables:
  R_BUILD_DIR: "build"
  KNITR_OUTPUT_DIR: "knitr"
  TEX_DIR: "Paper"
  OVERLEAF_ARTIFACTS_DIR: "overleaf"
  COMPOSE_FILES: --file docker-compose.yml --file docker-compose-gitlab.yml

.docker:
    tags:
        - docker
    services:
        - docker:18.09.7-dind
    image: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-compose-ci

tools:
  stage: tools
  extends: 
    - .docker
  script:
    - gitlab-docker-compose ${COMPOSE_FILES} --cache-from main build-package check-package knitr-paper pdflatex-figures pdflatex-paper
  
.build:
  stage: build
  extends: 
    - .docker
  variables:
    R_PACKAGE_SOURCE: .
  script:
    - mkdir -p "${R_BUILD_DIR}"
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} pull build-package
    - docker-compose ${COMPOSE_FILES} run build-package
    - export R_PACKAGE_ARCHIVE=`ls "${R_BUILD_DIR}"/pspline.inference*.tar.gz | head -n1`
    - printenv | grep '^R_PACKAGE_ARCHIVE=' >> build.env
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-package"
    paths:
      - "${R_BUILD_DIR}"
      - build.env
    when: always
  
build:
  extends: .build
  variables:
    BUILD_VIGNETTES: "TRUE"
  except: 
    - /^[Pp]aper([/-].*)?$/
    - /^validation(-.*)?$/
  
⚡️ build:
  extends: .build
  variables:
    BUILD_VIGNETTES: "FALSE"

check:
  stage: check
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} pull check-package
    - docker-compose ${COMPOSE_FILES} run check-package
  except:
    - /^[Pp]aper([/-].*)?$/
    - /^validation(-.*)?$/
  dependencies:
    - build

.knitr:
  stage: knitr
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} pull knitr-paper 
    - docker-compose ${COMPOSE_FILES} run knitr-paper
  dependencies:
    - ⚡️ build
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-knitr"
    paths:
      - "${KNITR_OUTPUT_DIR}"
    
knitr:
  extends: .knitr
  tags:
    - docker-cpu:comp8
  variables:
    RUN_VALIDATION: "TRUE"
  only:
    - /^validation(-.*)?$/

⚡️ knitr:
  extends: .knitr
  tags:
    - docker-mem:3
  variables:
    RUN_VALIDATION: "FALSE"
  only:
    - /^[Pp]aper([/-].*)?$/

overleaf:
  stage: overleaf
  extends: 
    - .docker
  script:
    - mkdir "${OVERLEAF_ARTIFACTS_DIR}"
    - docker-compose ${COMPOSE_FILES} pull pdflatex-figures 
    - docker-compose ${COMPOSE_FILES} run pdflatex-figures 
    - cp -r "${KNITR_OUTPUT_DIR}/PSplineInference.tex" "${TEX_DIR}/plos2015.bst" "${TEX_DIR}/PSplineInference.bib" "${KNITR_OUTPUT_DIR}/figures" "${OVERLEAF_ARTIFACTS_DIR}"
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-overleaf"
    paths:
      - "${OVERLEAF_ARTIFACTS_DIR}"
  only:
    - /^[Pp]aper([/-].*)?$/

tex:
  stage: tex
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} pull pdflatex-paper
    - docker-compose ${COMPOSE_FILES} run pdflatex-paper
    - mv "${OVERLEAF_ARTIFACTS_DIR}/PSplineInference.pdf" .
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-pdf"
    paths:
      - "PSplineInference.pdf"
  only: 
    - /^[Pp]aper([/-].*)?$/
